import Foundation
 
public enum DSColorsPreset: String, CaseIterable {
 case SurfaceUndercanvas
 case SurfaceCanvas
 case SurfaceTransparent
 case SurfaceLevel1
 case SurfaceLevel2
 case SurfaceLevel3
 case SurfaceLevel4
 case SurfaceInverse
 case SurfaceOverlay
 case SurfaceStaticDark
 case SurfaceStaticLight
 case TextPrimary
 case TextInverse
 case TextSecondary
 case TextTertiary
 case TextStaticDark
 case TextStaticLight
 case IconPrimary
 case IconInverse
 case IconSecondary
 case IconTertiary
 case BorderPrimary
 case BorderSecondary
 case BorderTertiary
 case BorderElevation
 case BorderStaticDark
 case BorderStaticLight
 case InputFillDefault
 case InputFillError
 case InputFillActive
 case InputFillCompleted
 case InputFillSuccess
 case InputFillWarning
 case InputFillInfo
 case InputBorderDefault
 case InputBorderError
 case InputBorderActive
 case InputBorderCompleted
 case InputBorderSuccess
 case InputBorderWarning
 case InputBorderInfo
 case InputTextDefault
 case InputTextError
 case InputTextActive
 case InputTextCompleted
 case InputTextSuccess
 case InputTextWarning
 case InputTextInfo
 case InputIconDefault
 case InputIconActive
 case InputIconCompleted
 case InputIconError
 case InputIconSuccess
 case InputIconWarning
 case InputIconInfo
 case MessagingFillError
 case MessagingFillSuccess
 case MessagingFillWarning
 case MessagingFillInfo
 case MessagingBorderError
 case MessagingBorderSuccess
 case MessagingBorderWarning
 case MessagingBorderInfo
 case MessagingIconError
 case MessagingIconSuccess
 case MessagingIconWarning
 case MessagingIconInfo
 case MessagingLinkTextDefault
 case MessagingLinkTextVisited
 case MessagingLinkIconDefault
 case MessagingLinkIconVisited
 case MessagingLinkUnderlineDefault
 case MessagingLinkUnderlineVisited
 case InteractivePrimaryFillDefault
 case InteractivePrimaryTextDefault
 case InteractivePrimaryIconDefault
 case InteractiveSecondaryFillDefault
 case InteractiveSecondaryBorderDefault
 case InteractiveSecondaryTextDefault
 case InteractiveSecondaryIconDefault
 case InteractiveDisabledA
 case InteractiveDisabledB
 case InteractiveDisabledC
 case InteractiveNegativeFillDefault
 case InteractiveNegativeBorderDefault
 case InteractiveNegativeTextDefault
 case InteractiveNegativeIconDefault
 case InteractiveLinkPrimaryTextDefault
 case InteractiveLinkPrimaryTextVisited
 case InteractiveLinkPrimaryIconDefault
 case InteractiveLinkPrimaryIconVisited
 case InteractiveLinkPrimaryUnderlineDefault
 case InteractiveLinkPrimaryUnderlineVisited
 case InteractiveLinkSecondaryTextDefault
 case InteractiveLinkSecondaryTextVisited
 case InteractiveLinkSecondaryIconDefault
 case InteractiveLinkSecondaryIconVisited
 case InteractiveLinkSecondaryUnderlineDefault
 case InteractiveLinkSecondaryUnderlineVisited
 case InteractiveChipPrimaryOnFillDefault
 case InteractiveChipPrimaryOnTextDefault
 case InteractiveChipPrimaryOnIconDefault
 case InteractiveChipPrimaryOffFillDefault
 case InteractiveChipPrimaryOffTextDefault
 case InteractiveChipPrimaryOffIconDefault
 case InteractiveChipPrimaryOffBorderDefault
 case InteractiveChipSecondaryOnTextDefault
 case InteractiveChipSecondaryOnFillDefault
 case InteractiveChipSecondaryOnBorderDefault
 case InteractiveChipSecondaryOnIconDefault
 case InteractiveChipSecondaryOffFillDefault
 case InteractiveChipSecondaryOffTextDefault
 case InteractiveChipSecondaryOffIconDefault
 case ActiveFill
 case ActiveText
 case ActiveBorder
 case ActiveIcon
 case FocusBorder
 case LabelPrimary
 case LabelSecondary
 case LabelCallout
 case FlagPrimaryFill
 case FlagPrimaryText
 case FlagPrimaryIcon
 case FlagSecondaryText
 case FlagSecondaryIcon
 case FlagCalloutFill
 case FlagCalloutText
 case FlagCalloutIcon
 case ToastFillInfo
 case ToastFillSuccess
 case ToastFillWarning
 case ToastFillError
 case ToastIconInfo
 case ToastIconSuccess
 case ToastIconWarning
 case ToastIconError
 case ToastTextInfo
 case ToastTextSuccess
 case ToastTextError
 case ToastTextWarning
 case ToastLinkInfoDefault
 case ToastLinkSuccessDefault
 case ToastLinkErrorDefault
 case ToastLinkWarningDefault
 case TooltipFill
 case TooltipText
 case TooltipIcon
 case ThemeBackground
 case ThemeForeground
 case ThemeCard
 case ThemeCardforeground
 case ThemePopover
 case ThemePopoverforeground
 case ThemePrimary
 case ThemePrimaryforeground
 case ThemeSecondary
 case ThemeSecondaryforeground
 case ThemeTertiary
 case ThemeTertiaryforeground
 case ThemeMuted
 case ThemeMutedforeground
 case ThemeBorder
 case ThemeInput
 case ThemeRing
 case ThemeInfo
 case ThemeInfoforeground
 case ThemeSuccess
 case ThemeSuccessforeground
 case ThemeWarning
 case ThemeWarningforeground
 case ThemeError
 case ThemeErrorforeground
 case ThemeDestructive
 case ThemeDestructiveforeground
 case ThemeChart1
 case ThemeChart2
 case ThemeChart3
 case ThemeChart4
 case ThemeChart5
}